// Datos falsos para simular una base de datos
export const tecnicos = [
  {
    id: 1,
    nombre: "Carlos Mendoza",
    especialidad: "electricidad",
    especialidadNombre: "Electricista",
    distritos: ["miraflores", "sanisidro"],
    distritosNombre: ["Miraflores", "San Isidro"],
    calificacion: 4,
    numResenas: 28,
    tarifaHora: 50,
    experiencia: "8 años",
    disponible: true,
    imagen: "/placeholder.svg?height=100&width=100",
  },
  {
    id: 2,
    nombre: "Ana Gutiérrez",
    especialidad: "plomeria",
    especialidadNombre: "Gasfitería",
    distritos: ["sanborja", "surco"],
    distritosNombre: ["San Borja", "Surco"],
    calificacion: 5,
    numResenas: 42,
    tarifaHora: 45,
    experiencia: "6 años",
    disponible: true,
    imagen: "/placeholder.svg?height=100&width=100",
  },
  {
    id: 3,
    nombre: "Jorge Salazar",
    especialidad: "pintura",
    especialidadNombre: "Pintor",
    distritos: ["lamolina", "surco"],
    distritosNombre: ["La Molina", "Surco"],
    calificacion: 4,
    numResenas: 15,
    tarifaHora: 40,
    experiencia: "5 años",
    disponible: false,
    imagen: "/placeholder.svg?height=100&width=100",
  },
  {
    id: 4,
    nombre: "Roberto Díaz",
    especialidad: "carpinteria",
    especialidadNombre: "Carpintero",
    distritos: ["miraflores", "barranco"],
    distritosNombre: ["Miraflores", "Barranco"],
    calificacion: 5,
    numResenas: 31,
    tarifaHora: 55,
    experiencia: "10 años",
    disponible: true,
    imagen: "/placeholder.svg?height=100&width=100",
  },
  {
    id: 5,
    nombre: "María Torres",
    especialidad: "cerrajeria",
    especialidadNombre: "Cerrajera",
    distritos: ["sanisidro", "miraflores", "surco"],
    distritosNombre: ["San Isidro", "Miraflores", "Surco"],
    calificacion: 4,
    numResenas: 19,
    tarifaHora: 60,
    experiencia: "7 años",
    disponible: true,
    imagen: "/placeholder.svg?height=100&width=100",
  },
  {
    id: 6,
    nombre: "Luis Vargas",
    especialidad: "electricidad",
    especialidadNombre: "Electricista",
    distritos: ["jesusmaría", "lince", "magdalena"],
    distritosNombre: ["Jesús María", "Lince", "Magdalena"],
    calificacion: 4,
    numResenas: 23,
    tarifaHora: 45,
    experiencia: "5 años",
    disponible: true,
    imagen: "/placeholder.svg?height=100&width=100",
  },
]

export const especialidades = [
  { value: "plomeria", label: "Gasfitería" },
  { value: "electricidad", label: "Electricidad" },
  { value: "pintura", label: "Pintura" },
  { value: "carpinteria", label: "Carpintería" },
  { value: "cerrajeria", label: "Cerrajería" },
]

export const distritos = [
  { value: "miraflores", label: "Miraflores" },
  { value: "sanisidro", label: "San Isidro" },
  { value: "surco", label: "Surco" },
  { value: "barranco", label: "Barranco" },
  { value: "lamolina", label: "La Molina" },
  { value: "sanborja", label: "San Borja" },
  { value: "lince", label: "Lince" },
  { value: "magdalena", label: "Magdalena" },
  { value: "jesusmaría", label: "Jesús María" },
]
